name: invenmanager
description: ""
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  mask_text_input_formatter: ^2.0.0

  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.0
  get_it: ^8.0.2
  firebase_storage: ^12.3.6
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  flutter_secure_storage: ^9.2.2
  cloud_firestore: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.14.1"


flutter:
  uses-material-design: true

  assets:
    - lib/assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/icon-dark-1024x1024.png"
  min_sdk_android: 21